### ISSUE TITLE
Compatibility with Cypress 10

### ISSUE THREAD

**Issue by JayceeZ** [badeball/cypress-configuration#1]
Hello,

I started having a look to what needs to be changed to make this work with Cypress 10.
I don't feel this is a lot of work, I will try and see if I can manage to make it work.

Mostly they removed completely
integrationFolder and testFiles
So as of now this fails on initialization because of the missing values.
Maybe changing to new e2e->specPattern might be sufficient.

Second stuff is that they created two types of folder, but I guess we could "hardcode" e2e as a first step.
After I'll have a look into setupNodeEvents, but I am unsure this is a necessary change to make this work again.

I'll come back after I tested this.

**Comment by badeball** [comment]
Compatibility with Cypress v10 has been partially added with https://github.com/badeball/cypress-configuration/commit/d2ea63cf12c8d4546f00e17a50261733997d6b5c and released as v3.0.0.
