### ISSUE TITLE
esbuild version

### ISSUE THREAD

**Issue by davidgiggs** [badeball/cypress-configuration#4]
Would if be possible to bump the version of the esbuild dependency in the @badeball/cypress-configuration package to align with that in the latest  @badeball/cypress-cucumber-preprocessor package (e.g. "esbuild": "^0.17.8",)

I noticed the following build error when attempting to use latest pre-processor:-

(alias) createEsbuildPlugin(configuration: ICypressConfiguration): Plugin
import createEsbuildPlugin
Type 'import("c:/Users/DGiggs/source/repos/myproject/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").Plugin' is not assignable to type 'import("c:/Users/DGiggs/source/repos/myproject/node_modules/esbuild/lib/main").Plugin'.
  Types of property 'setup' are incompatible.
    Type '(build: import("c:/Users/DGiggs/source/repos/myproject/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<...>' is not assignable to type '(build: import("c:/Users/DGiggs/source/repos/myproject/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>'.
      Types of parameters 'build' and 'build' are incompatible.
        Property 'onDispose' is missing in type 'import("c:/Users/DGiggs/source/repos/myproject/node_modules/esbuild/lib/main").PluginBuild' but required in type 'import("c:/Users/DGiggs/source/repos/myproject/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").PluginBuild'.ts(2322)

**Comment by davidgiggs** [comment]
myproject@0.0.1 C:\Users\DGiggs\source\repos\myproject
├─┬ @angular-devkit/build-angular@14.2.2
│ └── esbuild@0.15.5
├─┬ @badeball/cypress-cucumber-preprocessor@15.1.4
│ ├─┬ @badeball/cypress-configuration@4.2.0
│ │ └── esbuild@0.14.54
│ └── esbuild@0.17.12
└─┬ @bahmutov/cypress-esbuild-preprocessor@2.1.5
  └── esbuild@0.15.5 deduped

downgrading to 15.1.3 solves the issue, but upgrading cypress-configuration would keep them inline.

**Comment by badeball** [comment]
Can you provide an example of this?

**Comment by dcantu96** [comment]
I think I have the same problem @davidgiggs 

im using these deps for a react project: 
* `"@badeball/cypress-cucumber-preprocessor": "^19.2.0",`
* `"esbuild": "^0.19.8"`
* `"@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",`
* `"@testing-library/cypress": "^10.0.1",`
* `"cypress": "^13.6.1",`

this is my config

```tsx
import createBundler from '@bahmutov/cypress-esbuild-preprocessor'
import preprocessor from '@badeball/cypress-cucumber-preprocessor'
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild'
import { initPlugin } from '@frsource/cypress-plugin-visual-regression-diff/plugins'

function setupVisualDiffing(on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions) {
  initPlugin(on, config)
}

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions,
): Promise<Cypress.PluginConfigOptions> {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config)

  setupVisualDiffing(on, config)

  on(
    'file:preprocessor',
    createBundler({
      plugins: [createEsbuildPlugin(config)], // <--- here is the type error
    }),
  )

  // Make sure to return the config object as it might have been modified by the plugin.
  return config
}
```

then here is the config:
```tsx
export const cypressConfig: Cypress.ConfigOptions = {
  viewportWidth: 1280,
  viewportHeight: 720,
  e2e: {
    baseUrl: 'http://localhost:3000',
    specPattern: ['**/*.feature', '**/*.featureless.cy.ts'],
    setupNodeEvents,
  },
  component: {
    specPattern: ['cypress/component/**/*.cy.tsx'],
    devServer: {
      framework: 'react',
      bundler: 'vite',
    },
    setupNodeEvents(on, config) {
      setupVisualDiffing(on, config)
    },
    env: {
      pluginVisualRegressionUpdateImages: true,
    },
  },
}
````

heres a screenshot of the type error

![Screenshot 2023-12-07 at 5 24 10 p m](https://github.com/badeball/cypress-configuration/assets/32658690/6e2b4594-ecea-4100-9b38-a396bdde799c)

**Comment by badeball** [comment]
@dcantu96, I can't reproduce the issue using this information. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by dcantu96** [comment]
got it, are you ok with me using code sand box to reproduce?

**Comment by badeball** [comment]
I'm sure it's fine. The only thing that's important to me, is that you _verify_ that the information you provide me now, can in fact be used to reproduce your issue. IE. you need to download the sand box afterwards yourself, install dependencies and observe the error.
