### ISSUE TITLE
cypress-configuration Depends on "Vulnerable" inflight Library

### ISSUE THREAD

**Issue by yagcioe** [badeball/cypress-configuration#9]
While working on a snyk vunability issue (https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116 ) I've gone through all our dependencies.
It sees like this package has a transitive dependency to inflight through the package glob.

Updating to the latest version of glob resolves this issue.
You might want to take a look at these issues as well while i resarched about this issue.
https://github.com/mochajs/mocha/issues/5148
https://github.com/karma-runner/karma/issues/3888
https://www.npmjs.com/package/inflight

**Comment by badeball** [comment]
The most recent version of @badeball/cypress-cucumber-preprocessor no longer depends on this package (ie. this repository). Hence, this repository will be archived and the package discontinued. Hence, closing, as I will not be making any changes to it.
